### ISSUE TITLE
Groups value does not match in loop example

### ISSUE THREAD

**Issue by pbeshai** [bocoup/learn-ansible#25]
In Variables, Loops and Filters, under **Loops**, the groups value changes from `wheel` to `sudo`:

```
- name: add user testuser1
  user:
    name: testuser1
    state: present
    groups: wheel
- name: add user testuser2
  user:
    name: testuser2
    state: present
    groups: wheel
```

...can be equally defined like this:

```
- name: add several users
  user:
    name: "{{ item }}"
    state: present
    groups: sudo
  with_items:
     - testuser1
     - testuser2
```
